FROM registry.opensuse.org/opensuse/bci/gcc
RUN zypper --non-interactive in automake autoconf libtool diffutils
RUN zypper --non-interactive in liburcu-devel libjson-c-devel
RUN zypper --non-interactive in libuuid-devel libneon-devel liburing-devel
RUN zypper --non-interactive in coreutils nasm valgrind
RUN zypper --non-interactive in libopenssl-devel sqlite3-devel keyutils-devel
ENV SHEEPSRC=/usr/src/sheepdog

WORKDIR $SHEEPSRC
ADD . $SHEEPSRC
RUN ./autogen.sh
RUN ./configure --prefix=/usr --enable-etcd --disable-corosync --enable-nvmet --enable-io-uring && make && make install
