#!/bin/bash

# Test journal file replay

. ./common

_start_sheep 0 -j size=64M

_wait_for_sheep 1

_cluster_format -c 1

$DOG vdi create test 4G

# write something to vdi 'test'
echo "hello" | $DOG vdi write test 0 512
echo "sheepdog" | $DOG vdi write test 4M 512

# corrupt the vdi...  the journal is only left behind on an unclean exit,
# a graceful shutdown removes it (see clean_journal_file())
_kill_sheep_force 0
_delete_data_obj 0 807c2b2500000000
_delete_data_obj 0 007c2b25*

# do the journal replay
_start_sheep 0 -j size=64M
_wait_for_sheep 1

sleep 3

_vdi_list
$DOG vdi read test 0 512 | tr -d [:cntrl:]
echo -n ' '
$DOG vdi read test 4M 512 | tr -d [:cntrl:]
echo ''
