#!/bin/bash

# Test recovery process orphan object revival

. ./common

for i in 0 1 2 3; do
    _start_sheep $i
done
_wait_for_sheep 4
_cluster_format -c 3

$DOG vdi create test 16M -P

_vdi_list

_list_obj

_kill_sheep 3
_wait_for_sheep_stop 3

$DOG vdi delete test

_vdi_list

_start_sheep 3
_wait_for_sheep 4

_list_obj
