#!/bin/bash

# Test sheep -z/--zone

. ./common

err=0

function testStartZoneSucceeded
{
    zone="$1"
    _start_sheep 0 -z ${zone}
    _wait_for_sheep 1
    _node_list
    _cleanup
}

function testStartZoneFailed
{
    zone="$1"
    _start_sheep 0 -z ${zone} -e 2> /dev/null
    _wait_for_sheep_stop 0
    _cleanup
}

testStartZoneSucceeded 0
testStartZoneSucceeded 1
testStartZoneSucceeded 4294967295 # UINT32_MAX
testStartZoneFailed 4294967296 # UINT32_MAX + 1
testStartZoneFailed 9223372036854775808 # INT64_MAX + 1
testStartZoneFailed -1
testStartZoneFailed a
testStartZoneFailed 42a
testStartZoneFailed +
testStartZoneFailed -

exit $err
