#!/bin/bash

# Test sheep -V/--vnodes

. ./common

function testStartVnodesFailed
{
	( SHEEP_VNODES="$1" _start_sheep 0 ) && :
	_wait_for_sheep_stop 0
	_cleanup
	_setup
}

function testStartVnodesSucceeded
{
	SHEEP_VNODES="$1" _start_sheep 0
	_wait_for_sheep 1
	$DOG node list -r | _filter_ip_port
	_cleanup
	_setup
}

testStartVnodesSucceeded 1
testStartVnodesSucceeded 65535 # UINT16_MAX
testStartVnodesSucceeded 0
testStartVnodesFailed 65536 # UINT16_MAX + 1
testStartVnodesFailed 65537 # UINT16_MAX + 2
testStartVnodesFailed 4294967297 # UINT32_MAX + 2
testStartVnodesFailed -1
testStartVnodesFailed a
testStartVnodesFailed 42a
testStartVnodesFailed +
testStartVnodesFailed -
