name: sheepdog-etcd
services:
  sheep:
    image: sheepdog
    build:
      context: ../
      dockerfile: Dockerfile.sheepdog
    command: echo sheep container ready
  sheep0:
    image: sheepdog
    hostname: ${SHEEP0_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP0_IP}
      sheep-br:
    volumes:
      - sheep0-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7000:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE0_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP0_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=0
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep1:
    image: sheepdog
    hostname: ${SHEEP1_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP1_IP}
      sheep-br:
    volumes:
      - sheep1-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7001:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE1_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP1_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=1
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep2:
    image: sheepdog
    hostname: ${SHEEP2_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP2_IP}
      sheep-br:
    volumes:
      - sheep2-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7002:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE2_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP2_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=2
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep3:
    image: sheepdog
    hostname: ${SHEEP3_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP3_IP}
      sheep-br:
    volumes:
      - sheep3-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7003:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE3_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP3_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=3
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep4:
    image: sheepdog
    hostname: ${SHEEP4_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP4_IP}
      sheep-br:
    volumes:
      - sheep4-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7004:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE4_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP4_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=4
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep5:
    image: sheepdog
    hostname: ${SHEEP5_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP5_IP}
      sheep-br:
    volumes:
      - sheep5-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7005:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE5_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP5_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=5
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep6:
    image: sheepdog
    hostname: ${SHEEP6_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP6_IP}
      sheep-br:
    volumes:
      - sheep6-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7006:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE6_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP6_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=6
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep7:
    image: sheepdog
    hostname: ${SHEEP7_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP7_IP}
      sheep-br:
    volumes:
      - sheep7-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7007:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE7_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP7_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=7
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep8:
    image: sheepdog
    hostname: ${SHEEP8_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP8_IP}
      sheep-br:
    volumes:
      - sheep8-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7008:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE8_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP8_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=8
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep9:
    image: sheepdog
    hostname: ${SHEEP9_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP9_IP}
      sheep-br:
    volumes:
      - sheep9-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7009:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE9_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP9_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=9
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep10:
    image: sheepdog
    hostname: ${SHEEP10_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP10_IP}
      sheep-br:
    volumes:
      - sheep10-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7010:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE10_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP10_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=10
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep11:
    image: sheepdog
    hostname: ${SHEEP11_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP11_IP}
      sheep-br:
    volumes:
      - sheep11-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7011:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE11_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP11_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=11
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep12:
    image: sheepdog
    hostname: ${SHEEP12_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP12_IP}
      sheep-br:
    volumes:
      - sheep12-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7012:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE12_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP12_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=12
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep13:
    image: sheepdog
    hostname: ${SHEEP13_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP13_IP}
      sheep-br:
    volumes:
      - sheep13-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7013:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE13_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP13_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=13
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep14:
    image: sheepdog
    hostname: ${SHEEP14_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP14_IP}
      sheep-br:
    volumes:
      - sheep14-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7014:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE14_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP14_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=14
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep15:
    image: sheepdog
    hostname: ${SHEEP15_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP15_IP}
      sheep-br:
    volumes:
      - sheep15-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7015:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE15_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP15_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=15
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep16:
    image: sheepdog
    hostname: ${SHEEP16_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP16_IP}
      sheep-br:
    volumes:
      - sheep16-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7016:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE16_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP16_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=16
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep17:
    image: sheepdog
    hostname: ${SHEEP17_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP17_IP}
      sheep-br:
    volumes:
      - sheep17-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7017:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE17_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP17_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=17
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep18:
    image: sheepdog
    hostname: ${SHEEP18_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP18_IP}
      sheep-br:
    volumes:
      - sheep18-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7018:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE18_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP18_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=18
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep19:
    image: sheepdog
    hostname: ${SHEEP19_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP19_IP}
      sheep-br:
    volumes:
      - sheep19-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7019:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE19_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP19_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=19
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep20:
    image: sheepdog
    hostname: ${SHEEP20_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP20_IP}
      sheep-br:
    volumes:
      - sheep20-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7020:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE20_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP20_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=20
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep21:
    image: sheepdog
    hostname: ${SHEEP21_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP21_IP}
      sheep-br:
    volumes:
      - sheep21-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7021:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE21_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP21_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=21
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep22:
    image: sheepdog
    hostname: ${SHEEP22_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP22_IP}
      sheep-br:
    volumes:
      - sheep22-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7022:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE22_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP22_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=22
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f
  sheep23:
    image: sheepdog
    hostname: ${SHEEP23_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP23_IP}
      sheep-br:
    volumes:
      - sheep23-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7023:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE23_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP23_IP}
      - SHEEP_VNODES=${SHEEP_VNODES}
      - SHEEP_ZONE=23
      - VALGRIND=${VALGRIND}
    command: ${VALGRIND} /usr/sbin/sheep -f

volumes:
  sheep0-data:
  sheep1-data:
  sheep2-data:
  sheep3-data:
  sheep4-data:
  sheep5-data:
  sheep6-data:
  sheep7-data:
  sheep8-data:
  sheep9-data:
  sheep10-data:
  sheep11-data:
  sheep12-data:
  sheep13-data:
  sheep14-data:
  sheep15-data:
  sheep16-data:
  sheep17-data:
  sheep18-data:
  sheep19-data:
  sheep20-data:
  sheep21-data:
  sheep22-data:
  sheep23-data:

networks:
  etcd-br:
    external: true
    name: "etcd-internal"
  sheep-br:
    driver: bridge
