name: sheepdog-etcd
services:
  sheep:
    image: sheepdog
    build:
      context: ../
      dockerfile: Dockerfile.sheepdog
    command: echo sheep container ready
  sheep0:
    image: sheepdog
    hostname: ${SHEEP0_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP0_IP}
      sheep-br:
    volumes:
      - sheep0-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7000:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE0_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP0_IP}
    command: /usr/sbin/sheep -f
  sheep1:
    image: sheepdog
    hostname: ${SHEEP1_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP1_IP}
      sheep-br:
    volumes:
      - sheep1-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7001:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE1_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP1_IP}
    command: /usr/sbin/sheep -f
  sheep2:
    image: sheepdog
    hostname: ${SHEEP2_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP2_IP}
      sheep-br:
    volumes:
      - sheep2-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7002:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE2_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP2_IP}
    command: /usr/sbin/sheep -f
  sheep3:
    image: sheepdog
    hostname: ${SHEEP3_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP3_IP}
      sheep-br:
    volumes:
      - sheep3-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7003:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE3_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP3_IP}
    command: /usr/sbin/sheep -f
  sheep4:
    image: sheepdog
    hostname: ${SHEEP4_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP4_IP}
      sheep-br:
    volumes:
      - sheep4-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7004:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE4_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP4_IP}
    command: /usr/sbin/sheep -f
  sheep5:
    image: sheepdog
    hostname: ${SHEEP5_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP5_IP}
      sheep-br:
    volumes:
      - sheep5-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7005:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE5_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP5_IP}
    command: /usr/sbin/sheep -f
  sheep6:
    image: sheepdog
    hostname: ${SHEEP6_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP6_IP}
      sheep-br:
    volumes:
      - sheep6-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7006:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE6_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP6_IP}
    command: /usr/sbin/sheep -f
  sheep7:
    image: sheepdog
    hostname: ${SHEEP7_NAME}
    init: true
    networks:
      etcd-br:
        ipv4_address: ${SHEEP7_IP}
      sheep-br:
    volumes:
      - sheep7-data:/var/lib/sheep
    ports:
       - "127.0.0.1:7007:7000"
    environment:
      - SHEEP_CLUSTER_DRIVER=etcd:${NODE7_IP}
      - SHEEP_LOGGING=level=debug,dst=stdout
      - SHEEP_BASE_DIR=/var/lib/sheep
      - SHEEP_ADDR=${SHEEP7_IP}
    command: /usr/sbin/sheep -f

volumes:
  sheep0-data:
  sheep1-data:
  sheep2-data:
  sheep3-data:
  sheep4-data:
  sheep5-data:
  sheep6-data:
  sheep7-data:

networks:
  etcd-br:
    external: true
    name: "etcd-internal"
  sheep-br:
    driver: bridge
